// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnhrvzdktilgzbnxlkap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuaHJ2emRrdGlsZ3pibnhsa2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjQ0NTIsImV4cCI6MjA2MTAwMDQ1Mn0.ioRomGmZoxjOnS9vF74IPQE0s8wH6CEnvgGLQf9CTCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);